<?php
if (!defined('NOREQUIREUSER')) define('NOREQUIREUSER', '1');
if (!defined('NOREQUIREDB')) define('NOREQUIREDB', '1');
if (!defined('NOREQUIRESOC')) define('NOREQUIRESOC', '1');
if (!defined('NOCSRFCHECK')) define('NOCSRFCHECK', '1');
require '../../../main.inc.php';
header('Content-Type: application/javascript');
?>
(function(){
'use strict';
var selectedQty='1';
var selectedTerminal='';
function qs(s){return document.querySelector(s);} 
function qsa(s){return document.querySelectorAll(s);} 
function post(url,data){var body=new URLSearchParams(); Object.keys(data).forEach(function(k){body.append(k,data[k]);}); return fetch(url,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8'},body:body.toString()}).then(function(r){return r.json();});}
function money(v){var n=parseFloat(v||0); return n.toFixed(2);} 
function escapeHtml(str){return String(str||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function toast(msg){var t=document.createElement('div'); t.className='pos-toast'; t.textContent=msg; document.body.appendChild(t); setTimeout(function(){t.classList.add('show');},10); setTimeout(function(){t.classList.remove('show'); setTimeout(function(){t.remove();},220);},2200);} 
function syncQtyDisplay(){var el=qs('#pos-selected-qty'); if(el) el.textContent=selectedQty || '1';}
function syncTerminalChip(){var el=qs('#selected-terminal-chip'); if(el) el.textContent=selectedTerminal?('Terminal '+selectedTerminal):'Terminal ?';}
function clearQty(){selectedQty='1'; syncQtyDisplay();}
function keypadPress(key){if(key==='C'){clearQty(); return;} if(key==='.') { if(selectedQty.indexOf('.') !== -1) return; if(selectedQty==='1') selectedQty='0'; selectedQty += '.'; } else { if(selectedQty==='1') selectedQty=''; selectedQty += key; } if(selectedQty==='' || selectedQty==='.') selectedQty='1'; syncQtyDisplay();}
function productCellHtml(row){return '<div class="pos-row-product"><span class="pos-row-product-title">'+escapeHtml(row.product)+'</span><span class="pos-row-product-sub">Barcode: '+escapeHtml(row.barcode||'-')+'</span></div>';} 
function renderSearch(rows){var tbody=qs('#pos-search-results tbody'); if(!tbody) return; tbody.innerHTML=''; if(!rows||!rows.length){tbody.innerHTML='<tr><td colspan="4" class="opacitymedium pos-empty-note">No products found</td></tr>'; return;} rows.forEach(function(row){var tr=document.createElement('tr'); tr.innerHTML='<td>'+productCellHtml(row)+'</td><td class="right"><strong>'+money(row.price)+'</strong></td><td class="right">'+money(row.stock)+'</td><td class="center"><button type="button" class="pos-inline-add btn-add-product" data-id="'+row.id+'">Add</button></td>'; tbody.appendChild(tr);}); qsa('.btn-add-product').forEach(function(btn){btn.addEventListener('click',function(){addToCart(this.getAttribute('data-id'));});});}
function renderCart(cart){var tbody=qs('#pos-cart-table tbody'); if(!tbody) return; tbody.innerHTML=''; if(!cart||!cart.items||!cart.items.length){tbody.innerHTML='<tr><td colspan="6" class="opacitymedium pos-empty-note">Cart is empty</td></tr>'; qs('#cart-subtotal').textContent='0.00'; qs('#cart-tax').textContent='0.00'; var totalCell=qs('#payment-grand-total'); if(totalCell) totalCell.textContent='0.00'; return;} cart.items.forEach(function(item){var tr=document.createElement('tr'); tr.innerHTML='<td><div class="pos-row-product"><span class="pos-row-product-title">'+escapeHtml(item.product)+'</span><span class="pos-row-product-sub">Product ID: '+item.product_id+'</span></div></td><td class="right">'+money(item.qty)+'</td><td class="right">'+money(item.price)+'</td><td class="right">'+money(item.discount)+'</td><td class="right"><strong>'+money(item.total)+'</strong></td><td class="center"><button type="button" class="pos-inline-remove btn-remove-product" data-id="'+item.product_id+'">Remove</button></td>'; tbody.appendChild(tr);}); qsa('.btn-remove-product').forEach(function(btn){btn.addEventListener('click',function(){removeFromCart(this.getAttribute('data-id'));});}); qs('#cart-subtotal').textContent=money(cart.subtotal); qs('#cart-tax').textContent=money(cart.tax); var totalCell=qs('#payment-grand-total'); if(totalCell) totalCell.textContent=money(cart.total);} 
function searchProducts(){post(POSCORE_CONF.urls.searchProducts,{token:POSCORE_CONF.token,q:qs('#pos-search').value||'',barcode:qs('#pos-barcode').value||''}).then(function(json){if(!json.success){toast(json.error||'Search failed'); return;} renderSearch(json.rows); if(json.rows&&json.rows.length){toast('Products loaded');}}).catch(function(){toast('Search request failed');});}
function ensureTerminal(){if(selectedTerminal) return true; var modal=qs('#pos-terminal-modal'); if(modal) modal.classList.add('is-open'); toast('Select terminal first'); return false;}
function addToCart(productId){if(!ensureTerminal()) return; var qty=parseFloat(selectedQty||'1'); if(!qty || qty<=0) qty=1; post(POSCORE_CONF.urls.addToCart,{token:POSCORE_CONF.token,product_id:productId,qty:qty}).then(function(json){if(!json.success){toast(json.error||'Add to cart failed'); return;} renderCart(json.cart); toast('Item added'); clearQty();}).catch(function(){toast('Add to cart request failed');});}
function removeFromCart(productId){post(POSCORE_CONF.urls.removeFromCart,{token:POSCORE_CONF.token,product_id:productId}).then(function(json){if(!json.success){toast(json.error||'Remove failed'); return;} renderCart(json.cart); toast('Item removed');}).catch(function(){toast('Remove request failed');});}
function createInvoice(method){if(!ensureTerminal()) return; var customerId=qs('#pos-customer').value||'0'; if(customerId==='0'){toast('Please select customer'); return;} post(POSCORE_CONF.urls.createInvoice,{token:POSCORE_CONF.token,customer_id:customerId,payment_method:method,terminal:selectedTerminal}).then(function(json){if(!json.success){toast(json.error||'Sale failed'); return;} toast('Invoice created: '+(json.invoice_ref||json.invoice_id)); renderCart({items:[],subtotal:0,tax:0,total:0}); clearQty();}).catch(function(){toast('Invoice request failed');});}
function bindKeypad(){qsa('.pos-key').forEach(function(btn){btn.addEventListener('click',function(){keypadPress(this.getAttribute('data-key'));});});}
function bindTerminalModal(){var modal=qs('#pos-terminal-modal'); qsa('.pos-terminal-option').forEach(function(btn){btn.addEventListener('click',function(){selectedTerminal=this.getAttribute('data-terminal'); syncTerminalChip(); if(modal) modal.classList.remove('is-open'); toast('Terminal '+selectedTerminal+' selected');});}); var close=qs('#btn-close-terminal-modal'); if(close) close.addEventListener('click',function(){if(selectedTerminal && modal) modal.classList.remove('is-open');}); var open=qs('#btn-open-terminal-modal'); if(open) open.addEventListener('click',function(){if(modal) modal.classList.add('is-open');});}
function bindActions(){var s=qs('#btn-search-products'); if(s)s.addEventListener('click',searchProducts); var si=qs('#pos-search'); if(si)si.addEventListener('keypress',function(e){if(e.key==='Enter')searchProducts();}); var bi=qs('#pos-barcode'); if(bi)bi.addEventListener('keypress',function(e){if(e.key==='Enter')searchProducts();}); var fs=qs('#btn-focus-search'); if(fs) fs.addEventListener('click',function(){if(si) si.focus();}); qsa('.button-pay').forEach(function(btn){btn.addEventListener('click',function(){createInvoice(this.getAttribute('data-payment'));});}); var hold=qs('#btn-hold-order'); if(hold)hold.addEventListener('click',function(){toast('Hold order workflow can be added next');}); var clear=qs('#btn-clear-cart'); if(clear)clear.addEventListener('click',function(){renderCart({items:[],subtotal:0,tax:0,total:0}); toast('Cart cleared on screen'); clearQty();}); var nw=qs('#btn-new-sale'); if(nw)nw.addEventListener('click',function(){renderCart({items:[],subtotal:0,tax:0,total:0}); clearQty(); toast('Ready for a new sale');}); var his=qs('#btn-history'); if(his)his.addEventListener('click',function(){toast('History screen can be added in next package');}); var note=qs('#btn-free-text'); if(note)note.addEventListener('click',function(){toast('Free-text product action placeholder');}); var split=qs('#btn-split-sale'); if(split)split.addEventListener('click',function(){toast('Split sale action placeholder');});}
document.addEventListener('DOMContentLoaded',function(){syncQtyDisplay(); syncTerminalChip(); bindKeypad(); bindTerminalModal(); bindActions(); if((POSCORE_CONF.maxTerminals||0)===1){selectedTerminal='1'; syncTerminalChip(); var modal=qs('#pos-terminal-modal'); if(modal) modal.classList.remove('is-open');}});
})();
