<?php
//
// File generated by Dolibarr installer 22.0.4 on Feb 17, 2026
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root='http://www.dolibarr-pos-admin.com';
$dolibarr_main_document_root="C:/xampp/htdocs/dolibarr-copy/dolibarr";
$dolibarr_main_url_root_alt='/custom';
$dolibarr_main_document_root_alt="C:/xampp/htdocs/dolibarr-copy/dolibarr/custom";
$dolibarr_main_data_root="C:/xampp/htdocs/dolibarr-copy/documents";
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';
$dolibarr_main_db_name='kafoerp_erp';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='root';
$dolibarr_main_db_pass='';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='latin1';
$dolibarr_main_db_collation='latin1_swedish_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';


//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='617fd45bcb7b71f1d4b7a252facd643f';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
