CREATE TABLE llx_pos_shift (
  rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
  entity INTEGER NOT NULL DEFAULT 1,
  terminal_id INTEGER NOT NULL,
  cashier_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  shift_ref VARCHAR(64) NOT NULL,
  opened_at DATETIME NOT NULL,
  closed_at DATETIME DEFAULT NULL,
  opening_amount DECIMAL(24,8) NOT NULL DEFAULT 0,
  closing_amount DECIMAL(24,8) DEFAULT NULL,
  expected_amount DECIMAL(24,8) DEFAULT NULL,
  variance_amount DECIMAL(24,8) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 0,
  note_public TEXT DEFAULT NULL,
  note_private TEXT DEFAULT NULL,
  tms TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  fk_user_creat INTEGER DEFAULT NULL,
  fk_user_modif INTEGER DEFAULT NULL,
  UNIQUE KEY uk_pos_shift_entity_ref (entity, shift_ref),
  KEY idx_pos_shift_entity (entity),
  KEY idx_pos_shift_terminal (terminal_id),
  KEY idx_pos_shift_cashier (cashier_id),
  KEY idx_pos_shift_user (user_id),
  KEY idx_pos_shift_status (status),
  KEY idx_pos_shift_opened_at (opened_at)
) ENGINE=innodb;
