
CREATE TABLE llx_pos_terminal (
rowid INTEGER AUTO_INCREMENT PRIMARY KEY,
entity INTEGER,
ref VARCHAR(64),
label VARCHAR(255),
warehouse_id INTEGER,
status SMALLINT,
datec DATETIME,
tms TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=innodb;
